baseurl: "https://www.honlsoft.com/"
title: "honlSoft"
theme: "honlsoft"
languagecode: "en"
defaultcontentlanguage: "en"

paginate: 20
canonifyurls: true

disqusShortname: honlsoft

markup:
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: vs
    tabWidth: 4

params:
    author: "Jeremy Honl"
    title: "honlSoft"
    keywords:  "blog,developer,personal"
    github:  "https://github.com/jerhon"
    linkedin:  "https://linkedin.com/in/jhonl"

menu:
    home:
        - name:  "Blog"
          weight:  1
          url:  "/blog/"
        - name:  "About"
          weight:  2
          url:  "/about/"
        - name: "Projects"
          weight:  3
          url: "/projects/"